export const allowedOptionKeys = [
  'acl',
  'balance',
  'bind-process',
  'compression',
  'cookie',
  'default-server',
  'description',
  'disabled',
  'dispatch',
  'email-alert from',
  'email-alert level',
  'email-alert mailers',
  'email-alert myhostname',
  'email-alert to',
  'enabled',
  'errorfile',
  'errorfiles',
  'errorloc',
  'errorloc302',
  'errorloc303',
  'force-persist',
  'filter',
  'fullconn',
  'grace',
  'hash-type',
  'http-after-response',
  'http-check comment',
  'http-check connect',
  'http-check disable-on-404',
  'http-check expect',
  'http-check send',
  'http-check send-state',
  'http-check set-var',
  'http-check unset-var',
  'http-error',
  'http-request',
  'http-response',
  'http-reuse',
  'http-send-name-header',
  'id',
  'ignore-persist',
  'load-server-state-from-file',
  'log',
  'log-tag',
  'max-keep-alive-queue',
  'mode',
  'option abortonclose',
  'option accept-invalid-http-response',
  'option allbackups',
  'option checkcache',
  'option forwardfor',
  'option h1-case-adjust-bogus-server',
  'option http-buffer-request',
  'option http-keep-alive',
  'option http-no-delay',
  'option http-pretend-keepalive',
  'option http-server-close',
  'option httpchk',
  'option httpclose',
  'option http_proxy',
  'option independent-streams',
  'option ldap-check',
  'option external-check',
  'option log-health-checks',
  'option mysql-check',
  'option nolinger',
  'option originalto',
  'option persist',
  'option pgsql-check',
  'option prefer-last-server',
  'option redispatch',
  'option redis-check',
  'option smtpchk',
  'option splice-auto',
  'option splice-request',
  'option splice-response',
  'option spop-check',
  'option srvtcpka',
  'option ssl-hello-chk',
  'option tcp-check',
  'option tcp-smart-connect',
  'option tcpka',
  'option tcplog',
  'option transparent',
  'external-check command',
  'external-check path',
  'persist rdp-cookie',
  'redirect',
  'retries',
  'retry-on',
  'server',
  'server-state-file-name',
  'server-template',
  'source',
  'srvtcpka-cnt',
  'srvtcpka-idle',
  'srvtcpka-intvl',
  'stats admin',
  'stats auth',
  'stats enable',
  'stats hide-version',
  'stats http-request',
  'stats realm',
  'stats refresh',
  'stats scope',
  'stats show-desc',
  'stats show-legends',
  'stats show-node',
  'stats uri',
  'stick match',
  'stick on',
  'stick store-request',
  'stick store-response',
  'stick-table',
  'tcp-check comment',
  'tcp-check connect',
  'tcp-check expect',
  'tcp-check send',
  'tcp-check send-lf',
  'tcp-check send-binary',
  'tcp-check send-binary-lf',
  'tcp-check set-var',
  'tcp-check unset-var',
  'tcp-request content',
  'tcp-request inspect-delay',
  'tcp-response content',
  'tcp-response inspect-delay',
  'timeout check',
  'timeout connect',
  'timeout http-keep-alive',
  'timeout http-request',
  'timeout queue',
  'timeout server',
  'timeout server-fin',
  'timeout tarpit',
  'timeout tunnel',
  'transparent',
  'use-fcgi-app',
  'use-server',
];
