import { matchExactKey } from '../../utils/match-option';
import { haproxyOptionsKeys } from '../../const';

export const allowedOptionKeys = [
  haproxyOptionsKeys['acl'],
  haproxyOptionsKeys['balance'],
  haproxyOptionsKeys['bind-process'],
  haproxyOptionsKeys['compression'],
  haproxyOptionsKeys['cookie'],
  haproxyOptionsKeys['default-server'],
  haproxyOptionsKeys['description'],
  haproxyOptionsKeys['disabled'],
  haproxyOptionsKeys['dispatch'],
  haproxyOptionsKeys['email-alert from'],
  haproxyOptionsKeys['email-alert level'],
  haproxyOptionsKeys['email-alert mailers'],
  haproxyOptionsKeys['email-alert myhostname'],
  haproxyOptionsKeys['email-alert to'],
  haproxyOptionsKeys['enabled'],
  haproxyOptionsKeys['errorfile'],
  haproxyOptionsKeys['errorfiles'],
  haproxyOptionsKeys['errorloc'],
  haproxyOptionsKeys['errorloc302'],
  haproxyOptionsKeys['errorloc303'],
  haproxyOptionsKeys['force-persist'],
  haproxyOptionsKeys['filter'],
  haproxyOptionsKeys['fullconn'],
  haproxyOptionsKeys['grace'],
  haproxyOptionsKeys['hash-type'],
  haproxyOptionsKeys['http-after-response'],
  haproxyOptionsKeys['http-check comment'],
  haproxyOptionsKeys['http-check connect'],
  haproxyOptionsKeys['http-check disable-on-404'],
  haproxyOptionsKeys['http-check expect'],
  haproxyOptionsKeys['http-check send'],
  haproxyOptionsKeys['http-check send-state'],
  haproxyOptionsKeys['http-check set-var'],
  haproxyOptionsKeys['http-check unset-var'],
  haproxyOptionsKeys['http-error'],
  haproxyOptionsKeys['http-request'],
  haproxyOptionsKeys['http-response'],
  haproxyOptionsKeys['http-reuse'],
  haproxyOptionsKeys['http-send-name-header'],
  haproxyOptionsKeys['id'],
  haproxyOptionsKeys['ignore-persist'],
  haproxyOptionsKeys['load-server-state-from-file'],
  haproxyOptionsKeys['log'],
  haproxyOptionsKeys['log-tag'],
  haproxyOptionsKeys['max-keep-alive-queue'],
  haproxyOptionsKeys['mode'],
  haproxyOptionsKeys['option abortonclose'],
  haproxyOptionsKeys['option accept-invalid-http-response'],
  haproxyOptionsKeys['option allbackups'],
  haproxyOptionsKeys['option checkcache'],
  haproxyOptionsKeys['option forwardfor'],
  haproxyOptionsKeys['option h1-case-adjust-bogus-server'],
  haproxyOptionsKeys['option http-buffer-request'],
  haproxyOptionsKeys['option http-keep-alive'],
  haproxyOptionsKeys['option http-no-delay'],
  haproxyOptionsKeys['option http-pretend-keepalive'],
  haproxyOptionsKeys['option http-server-close'],
  haproxyOptionsKeys['option httpchk'],
  haproxyOptionsKeys['option httpclose'],
  haproxyOptionsKeys['option http_proxy'],
  haproxyOptionsKeys['option independent-streams'],
  haproxyOptionsKeys['option ldap-check'],
  haproxyOptionsKeys['option external-check'],
  haproxyOptionsKeys['option log-health-checks'],
  haproxyOptionsKeys['option mysql-check'],
  haproxyOptionsKeys['option nolinger'],
  haproxyOptionsKeys['option originalto'],
  haproxyOptionsKeys['option persist'],
  haproxyOptionsKeys['option pgsql-check'],
  haproxyOptionsKeys['option prefer-last-server'],
  haproxyOptionsKeys['option redispatch'],
  haproxyOptionsKeys['option redis-check'],
  haproxyOptionsKeys['option smtpchk'],
  haproxyOptionsKeys['option splice-auto'],
  haproxyOptionsKeys['option splice-request'],
  haproxyOptionsKeys['option splice-response'],
  haproxyOptionsKeys['option spop-check'],
  haproxyOptionsKeys['option srvtcpka'],
  haproxyOptionsKeys['option ssl-hello-chk'],
  haproxyOptionsKeys['option tcp-check'],
  haproxyOptionsKeys['option tcp-smart-connect'],
  haproxyOptionsKeys['option tcpka'],
  haproxyOptionsKeys['option tcplog'],
  haproxyOptionsKeys['option transparent'],
  haproxyOptionsKeys['external-check command'],
  haproxyOptionsKeys['external-check path'],
  haproxyOptionsKeys['persist rdp-cookie'],
  haproxyOptionsKeys['redirect'],
  haproxyOptionsKeys['retries'],
  haproxyOptionsKeys['retry-on'],
  haproxyOptionsKeys['server'],
  haproxyOptionsKeys['server-state-file-name'],
  haproxyOptionsKeys['server-template'],
  haproxyOptionsKeys['source'],
  haproxyOptionsKeys['srvtcpka-cnt'],
  haproxyOptionsKeys['srvtcpka-idle'],
  haproxyOptionsKeys['srvtcpka-intvl'],
  haproxyOptionsKeys['stats admin'],
  haproxyOptionsKeys['stats auth'],
  haproxyOptionsKeys['stats enable'],
  haproxyOptionsKeys['stats hide-version'],
  haproxyOptionsKeys['stats http-request'],
  haproxyOptionsKeys['stats realm'],
  haproxyOptionsKeys['stats refresh'],
  haproxyOptionsKeys['stats scope'],
  haproxyOptionsKeys['stats show-desc'],
  haproxyOptionsKeys['stats show-legends'],
  haproxyOptionsKeys['stats show-node'],
  haproxyOptionsKeys['stats uri'],
  haproxyOptionsKeys['stick match'],
  haproxyOptionsKeys['stick on'],
  haproxyOptionsKeys['stick store-request'],
  haproxyOptionsKeys['stick store-response'],
  haproxyOptionsKeys['stick-table'],
  haproxyOptionsKeys['tcp-check comment'],
  haproxyOptionsKeys['tcp-check connect'],
  haproxyOptionsKeys['tcp-check expect'],
  haproxyOptionsKeys['tcp-check send'],
  haproxyOptionsKeys['tcp-check send-lf'],
  haproxyOptionsKeys['tcp-check send-binary'],
  haproxyOptionsKeys['tcp-check send-binary-lf'],
  haproxyOptionsKeys['tcp-check set-var'],
  haproxyOptionsKeys['tcp-check unset-var'],
  haproxyOptionsKeys['tcp-request content'],
  haproxyOptionsKeys['tcp-request inspect-delay'],
  haproxyOptionsKeys['tcp-response content'],
  haproxyOptionsKeys['tcp-response inspect-delay'],
  haproxyOptionsKeys['timeout check'],
  haproxyOptionsKeys['timeout connect'],
  haproxyOptionsKeys['timeout http-keep-alive'],
  haproxyOptionsKeys['timeout http-request'],
  haproxyOptionsKeys['timeout queue'],
  haproxyOptionsKeys['timeout server'],
  haproxyOptionsKeys['timeout server-fin'],
  haproxyOptionsKeys['timeout tarpit'],
  haproxyOptionsKeys['timeout tunnel'],
  haproxyOptionsKeys['transparent'],
  haproxyOptionsKeys['use-fcgi-app'],
  haproxyOptionsKeys['use-server'],
];

export const isSupportedInBackend = (key: string): boolean => matchExactKey(key, allowedOptionKeys);
