import { matchExactKey } from '../../utils/match-option';
import { haproxyOptionsKeys } from '../../const';

export const allowedOptionKeys = [
  haproxyOptionsKeys['backlog'],
  haproxyOptionsKeys['balance'],
  haproxyOptionsKeys['bind-process'],
  haproxyOptionsKeys['clitcpka-cnt'],
  haproxyOptionsKeys['clitcpka-idle'],
  haproxyOptionsKeys['clitcpka-intvl'],
  haproxyOptionsKeys['compression'],
  haproxyOptionsKeys['cookie'],
  haproxyOptionsKeys['default-server'],
  haproxyOptionsKeys['default_backend'],
  haproxyOptionsKeys['disabled'],
  haproxyOptionsKeys['email-alert from'],
  haproxyOptionsKeys['email-alert level'],
  haproxyOptionsKeys['email-alert mailers'],
  haproxyOptionsKeys['email-alert myhostname'],
  haproxyOptionsKeys['email-alert to'],
  haproxyOptionsKeys['enabled'],
  haproxyOptionsKeys['errorfile'],
  haproxyOptionsKeys['errorfiles'],
  haproxyOptionsKeys['errorloc'],
  haproxyOptionsKeys['errorloc302'],
  haproxyOptionsKeys['errorloc303'],
  haproxyOptionsKeys['fullconn'],
  haproxyOptionsKeys['grace'],
  haproxyOptionsKeys['hash-type'],
  haproxyOptionsKeys['http-check comment'],
  haproxyOptionsKeys['http-check connect'],
  haproxyOptionsKeys['http-check disable-on-404'],
  haproxyOptionsKeys['http-check expect'],
  haproxyOptionsKeys['http-check send'],
  haproxyOptionsKeys['http-check send-state'],
  haproxyOptionsKeys['http-check set-var'],
  haproxyOptionsKeys['http-check unset-var'],
  haproxyOptionsKeys['http-error'],
  haproxyOptionsKeys['http-reuse'],
  haproxyOptionsKeys['load-server-state-from-file'],
  haproxyOptionsKeys['log'],
  haproxyOptionsKeys['log-format'],
  haproxyOptionsKeys['log-format-sd'],
  haproxyOptionsKeys['log-tag'],
  haproxyOptionsKeys['max-keep-alive-queue'],
  haproxyOptionsKeys['maxconn'],
  haproxyOptionsKeys['mode'],
  haproxyOptionsKeys['monitor-uri'],
  haproxyOptionsKeys['option abortonclose'],
  haproxyOptionsKeys['option accept-invalid-http-request'],
  haproxyOptionsKeys['option accept-invalid-http-response'],
  haproxyOptionsKeys['option allbackups'],
  haproxyOptionsKeys['option checkcache'],
  haproxyOptionsKeys['option clitcpka'],
  haproxyOptionsKeys['option contstats'],
  haproxyOptionsKeys['option disable-h2-upgrade'],
  haproxyOptionsKeys['option dontlog-normal'],
  haproxyOptionsKeys['option dontlognull'],
  haproxyOptionsKeys['option forwardfor'],
  haproxyOptionsKeys['option h1-case-adjust-bogus-client'],
  haproxyOptionsKeys['option h1-case-adjust-bogus-server'],
  haproxyOptionsKeys['option http-buffer-request'],
  haproxyOptionsKeys['option http-ignore-probes'],
  haproxyOptionsKeys['option http-keep-alive'],
  haproxyOptionsKeys['option http-no-delay'],
  haproxyOptionsKeys['option http-pretend-keepalive'],
  haproxyOptionsKeys['option http-server-close'],
  haproxyOptionsKeys['option http-use-proxy-header'],
  haproxyOptionsKeys['option httpchk'],
  haproxyOptionsKeys['option httpclose'],
  haproxyOptionsKeys['option httplog'],
  haproxyOptionsKeys['option http_proxy'],
  haproxyOptionsKeys['option independent-streams'],
  haproxyOptionsKeys['option ldap-check'],
  haproxyOptionsKeys['option external-check'],
  haproxyOptionsKeys['option log-health-checks'],
  haproxyOptionsKeys['option log-separate-errors'],
  haproxyOptionsKeys['option logasap'],
  haproxyOptionsKeys['option mysql-check'],
  haproxyOptionsKeys['option nolinger'],
  haproxyOptionsKeys['option originalto'],
  haproxyOptionsKeys['option persist'],
  haproxyOptionsKeys['option pgsql-check'],
  haproxyOptionsKeys['option prefer-last-server'],
  haproxyOptionsKeys['option redispatch'],
  haproxyOptionsKeys['option redis-check'],
  haproxyOptionsKeys['option smtpchk'],
  haproxyOptionsKeys['option socket-stats'],
  haproxyOptionsKeys['option splice-auto'],
  haproxyOptionsKeys['option splice-request'],
  haproxyOptionsKeys['option splice-response'],
  haproxyOptionsKeys['option srvtcpka'],
  haproxyOptionsKeys['option ssl-hello-chk'],
  haproxyOptionsKeys['option tcp-check'],
  haproxyOptionsKeys['option tcp-smart-accept'],
  haproxyOptionsKeys['option tcp-smart-connect'],
  haproxyOptionsKeys['option tcpka'],
  haproxyOptionsKeys['option tcplog'],
  haproxyOptionsKeys['option transparent'],
  haproxyOptionsKeys['external-check command'],
  haproxyOptionsKeys['external-check path'],
  haproxyOptionsKeys['persist rdp-cookie'],
  haproxyOptionsKeys['rate-limit sessions'],
  haproxyOptionsKeys['retries'],
  haproxyOptionsKeys['retry-on'],
  haproxyOptionsKeys['server-state-file-name'],
  haproxyOptionsKeys['source'],
  haproxyOptionsKeys['srvtcpka-cnt'],
  haproxyOptionsKeys['srvtcpka-idle'],
  haproxyOptionsKeys['srvtcpka-intvl'],
  haproxyOptionsKeys['stats auth'],
  haproxyOptionsKeys['stats enable'],
  haproxyOptionsKeys['stats hide-version'],
  haproxyOptionsKeys['stats realm'],
  haproxyOptionsKeys['stats refresh'],
  haproxyOptionsKeys['stats scope'],
  haproxyOptionsKeys['stats show-desc'],
  haproxyOptionsKeys['stats show-legends'],
  haproxyOptionsKeys['stats show-node'],
  haproxyOptionsKeys['stats uri'],
  haproxyOptionsKeys['tcp-check comment'],
  haproxyOptionsKeys['tcp-check connect'],
  haproxyOptionsKeys['tcp-check expect'],
  haproxyOptionsKeys['tcp-check send'],
  haproxyOptionsKeys['tcp-check send-lf'],
  haproxyOptionsKeys['tcp-check send-binary'],
  haproxyOptionsKeys['tcp-check send-binary-lf'],
  haproxyOptionsKeys['tcp-check set-var'],
  haproxyOptionsKeys['tcp-check unset-var'],
  haproxyOptionsKeys['timeout check'],
  haproxyOptionsKeys['timeout client'],
  haproxyOptionsKeys['timeout client-fin'],
  haproxyOptionsKeys['timeout connect'],
  haproxyOptionsKeys['timeout http-keep-alive'],
  haproxyOptionsKeys['timeout http-request'],
  haproxyOptionsKeys['timeout queue'],
  haproxyOptionsKeys['timeout server'],
  haproxyOptionsKeys['timeout server-fin'],
  haproxyOptionsKeys['timeout tarpit'],
  haproxyOptionsKeys['timeout tunnel'],
  haproxyOptionsKeys['transparent'],
  haproxyOptionsKeys['unique-id-format'],
  haproxyOptionsKeys['unique-id-header'],
];

export const isSupportedInDefaults = (key: string): boolean => matchExactKey(key, allowedOptionKeys);
