export const allowedOptionKeys = [
  'backlog',
  'balance',
  'bind-process',
  'clitcpka-cnt',
  'clitcpka-idle',
  'clitcpka-intvl',
  'compression',
  'cookie',
  'default-server',
  'default_backend',
  'disabled',
  'email-alert from',
  'email-alert level',
  'email-alert mailers',
  'email-alert myhostname',
  'email-alert to',
  'enabled',
  'errorfile',
  'errorfiles',
  'errorloc',
  'errorloc302',
  'errorloc303',
  'fullconn',
  'grace',
  'hash-type',
  'http-check comment',
  'http-check connect',
  'http-check disable-on-404',
  'http-check expect',
  'http-check send',
  'http-check send-state',
  'http-check set-var',
  'http-check unset-var',
  'http-error',
  'http-reuse',
  'load-server-state-from-file',
  'log',
  'log-format',
  'log-format-sd',
  'log-tag',
  'max-keep-alive-queue',
  'maxconn',
  'mode',
  'monitor-uri',
  'option abortonclose',
  'option accept-invalid-http-request',
  'option accept-invalid-http-response',
  'option allbackups',
  'option checkcache',
  'option clitcpka',
  'option contstats',
  'option disable-h2-upgrade',
  'option dontlog-normal',
  'option dontlognull',
  'option forwardfor',
  'option h1-case-adjust-bogus-client',
  'option h1-case-adjust-bogus-server',
  'option http-buffer-request',
  'option http-ignore-probes',
  'option http-keep-alive',
  'option http-no-delay',
  'option http-pretend-keepalive',
  'option http-server-close',
  'option http-use-proxy-header',
  'option httpchk',
  'option httpclose',
  'option httplog',
  'option http_proxy',
  'option independent-streams',
  'option ldap-check',
  'option external-check',
  'option log-health-checks',
  'option log-separate-errors',
  'option logasap',
  'option mysql-check',
  'option nolinger',
  'option originalto',
  'option persist',
  'option pgsql-check',
  'option prefer-last-server',
  'option redispatch',
  'option redis-check',
  'option smtpchk',
  'option socket-stats',
  'option splice-auto',
  'option splice-request',
  'option splice-response',
  'option srvtcpka',
  'option ssl-hello-chk',
  'option tcp-check',
  'option tcp-smart-accept',
  'option tcp-smart-connect',
  'option tcpka',
  'option tcplog',
  'option transparent',
  'external-check command',
  'external-check path',
  'persist rdp-cookie',
  'rate-limit sessions',
  'retries',
  'retry-on',
  'server-state-file-name',
  'source',
  'srvtcpka-cnt',
  'srvtcpka-idle',
  'srvtcpka-intvl',
  'stats auth',
  'stats enable',
  'stats hide-version',
  'stats realm',
  'stats refresh',
  'stats scope',
  'stats show-desc',
  'stats show-legends',
  'stats show-node',
  'stats uri',
  'tcp-check comment',
  'tcp-check connect',
  'tcp-check expect',
  'tcp-check send',
  'tcp-check send-lf',
  'tcp-check send-binary',
  'tcp-check send-binary-lf',
  'tcp-check set-var',
  'tcp-check unset-var',
  'timeout check',
  'timeout client',
  'timeout client-fin',
  'timeout connect',
  'timeout http-keep-alive',
  'timeout http-request',
  'timeout queue',
  'timeout server',
  'timeout server-fin',
  'timeout tarpit',
  'timeout tunnel',
  'transparent',
  'unique-id-format',
  'unique-id-header',
];
