export const haproxyOptionsKeys = {
  acl: 'acl',
  backlog: 'backlog',
  balance: 'balance',
  bind: 'bind',
  'bind-process': 'bind-process',
  'capture cookie': 'capture cookie',
  'capture request header': 'capture request header',
  'capture response header': 'capture response header',
  'clitcpka-cnt': 'clitcpka-cnt',
  'clitcpka-idle': 'clitcpka-idle',
  'clitcpka-intvl': 'clitcpka-intvl',
  compression: 'compression',
  cookie: 'cookie',
  'declare capture': 'declare capture',
  'default-server': 'default-server',
  'default_backend': 'default_backend',
  description: 'description',
  disabled: 'disabled',
  dispatch: 'dispatch',
  'email-alert from': 'email-alert from',
  'email-alert level': 'email-alert level',
  'email-alert mailers': 'email-alert mailers',
  'email-alert myhostname': 'email-alert myhostname',
  'email-alert to': 'email-alert to',
  enabled: 'enabled',
  errorfile: 'errorfile',
  errorfiles: 'errorfiles',
  errorloc: 'errorloc',
  'errorloc302': 'errorloc302',
  'errorloc303': 'errorloc303',
  'force-persist': 'force-persist',
  filter: 'filter',
  fullconn: 'fullconn',
  grace: 'grace',
  'hash-type': 'hash-type',
  'http-after-response': 'http-after-response',
  'http-check comment': 'http-check comment',
  'http-check connect': 'http-check connect',
  'http-check disable-on-404': 'http-check disable-on-404',
  'http-check expect': 'http-check expect',
  'http-check send': 'http-check send',
  'http-check send-state': 'http-check send-state',
  'http-check set-var': 'http-check set-var',
  'http-check unset-var': 'http-check unset-var',
  'http-error': 'http-error',
  'http-request': 'http-request',
  'http-response': 'http-response',
  'http-reuse': 'http-reuse',
  'http-send-name-header': 'http-send-name-header',
  id: 'id',
  'ignore-persist': 'ignore-persist',
  'load-server-state-from-file': 'load-server-state-from-file',
  log: 'log',
  'log-format': 'log-format',
  'log-format-sd': 'log-format-sd',
  'log-tag': 'log-tag',
  'max-keep-alive-queue': 'max-keep-alive-queue',
  maxconn: 'maxconn',
  mode: 'mode',
  'monitor fail': 'monitor fail',
  'monitor-uri': 'monitor-uri',
  'option abortonclose': 'option abortonclose',
  'option accept-invalid-http-request': 'option accept-invalid-http-request',
  'option accept-invalid-http-response': 'option accept-invalid-http-response',
  'option allbackups': 'option allbackups',
  'option checkcache': 'option checkcache',
  'option clitcpka': 'option clitcpka',
  'option contstats': 'option contstats',
  'option disable-h2-upgrade': 'option disable-h2-upgrade',
  'option dontlog-normal': 'option dontlog-normal',
  'option dontlognull': 'option dontlognull',
  'option forwardfor': 'option forwardfor',
  'option h1-case-adjust-bogus-client': 'option h1-case-adjust-bogus-client',
  'option h1-case-adjust-bogus-server': 'option h1-case-adjust-bogus-server',
  'option http-buffer-request': 'option http-buffer-request',
  'option http-ignore-probes': 'option http-ignore-probes',
  'option http-keep-alive': 'option http-keep-alive',
  'option http-no-delay': 'option http-no-delay',
  'option http-pretend-keepalive': 'option http-pretend-keepalive',
  'option http-server-close': 'option http-server-close',
  'option http-use-proxy-header': 'option http-use-proxy-header',
  'option httpchk': 'option httpchk',
  'option httpclose': 'option httpclose',
  'option httplog': 'option httplog',
  'option http_proxy': 'option http_proxy',
  'option independent-streams': 'option independent-streams',
  'option ldap-check': 'option ldap-check',
  'option external-check': 'option external-check',
  'option log-health-checks': 'option log-health-checks',
  'option log-separate-errors': 'option log-separate-errors',
  'option logasap': 'option logasap',
  'option mysql-check': 'option mysql-check',
  'option nolinger': 'option nolinger',
  'option originalto': 'option originalto',
  'option persist': 'option persist',
  'option pgsql-check': 'option pgsql-check',
  'option prefer-last-server': 'option prefer-last-server',
  'option redispatch': 'option redispatch',
  'option redis-check': 'option redis-check',
  'option smtpchk': 'option smtpchk',
  'option socket-stats': 'option socket-stats',
  'option splice-auto': 'option splice-auto',
  'option splice-request': 'option splice-request',
  'option splice-response': 'option splice-response',
  'option spop-check': 'option spop-check',
  'option srvtcpka': 'option srvtcpka',
  'option ssl-hello-chk': 'option ssl-hello-chk',
  'option tcp-check': 'option tcp-check',
  'option tcp-smart-accept': 'option tcp-smart-accept',
  'option tcp-smart-connect': 'option tcp-smart-connect',
  'option tcpka': 'option tcpka',
  'option tcplog': 'option tcplog',
  'option transparent': 'option transparent',
  'external-check command': 'external-check command',
  'external-check path': 'external-check path',
  'persist rdp-cookie': 'persist rdp-cookie',
  'rate-limit sessions': 'rate-limit sessions',
  redirect: 'redirect',
  retries: 'retries',
  'retry-on': 'retry-on',
  server: 'server',
  'server-state-file-name': 'server-state-file-name',
  'server-template': 'server-template',
  source: 'source',
  'srvtcpka-cnt': 'srvtcpka-cnt',
  'srvtcpka-idle': 'srvtcpka-idle',
  'srvtcpka-intvl': 'srvtcpka-intvl',
  'stats admin': 'stats admin',
  'stats auth': 'stats auth',
  'stats enable': 'stats enable',
  'stats hide-version': 'stats hide-version',
  'stats http-request': 'stats http-request',
  'stats realm': 'stats realm',
  'stats refresh': 'stats refresh',
  'stats scope': 'stats scope',
  'stats show-desc': 'stats show-desc',
  'stats show-legends': 'stats show-legends',
  'stats show-node': 'stats show-node',
  'stats uri': 'stats uri',
  'stick match': 'stick match',
  'stick on': 'stick on',
  'stick store-request': 'stick store-request',
  'stick store-response': 'stick store-response',
  'stick-table': 'stick-table',
  'tcp-check comment': 'tcp-check comment',
  'tcp-check connect': 'tcp-check connect',
  'tcp-check expect': 'tcp-check expect',
  'tcp-check send': 'tcp-check send',
  'tcp-check send-lf': 'tcp-check send-lf',
  'tcp-check send-binary': 'tcp-check send-binary',
  'tcp-check send-binary-lf': 'tcp-check send-binary-lf',
  'tcp-check set-var': 'tcp-check set-var',
  'tcp-check unset-var': 'tcp-check unset-var',
  'tcp-request connection': 'tcp-request connection',
  'tcp-request content': 'tcp-request content',
  'tcp-request inspect-delay': 'tcp-request inspect-delay',
  'tcp-request session': 'tcp-request session',
  'tcp-response content': 'tcp-response content',
  'tcp-response inspect-delay': 'tcp-response inspect-delay',
  'timeout check': 'timeout check',
  'timeout client': 'timeout client',
  'timeout client-fin': 'timeout client-fin',
  'timeout connect': 'timeout connect',
  'timeout http-keep-alive': 'timeout http-keep-alive',
  'timeout http-request': 'timeout http-request',
  'timeout queue': 'timeout queue',
  'timeout server': 'timeout server',
  'timeout server-fin': 'timeout server-fin',
  'timeout tarpit': 'timeout tarpit',
  'timeout tunnel': 'timeout tunnel',
  transparent: 'transparent',
  'unique-id-format': 'unique-id-format',
  'unique-id-header': 'unique-id-header',
  'use_backend': 'use_backend',
  'use-fcgi-app': 'use-fcgi-app',
  'use-server': 'use-server',
  'ca-base': 'ca-base',
  chroot: 'chroot',
  'crt-base': 'crt-base',
  'cpu-map': 'cpu-map',
  daemon: 'daemon',
  'deviceatlas-json-file': 'deviceatlas-json-file',
  'deviceatlas-log-level': 'deviceatlas-log-level',
  'deviceatlas-separator': 'deviceatlas-separator',
  'deviceatlas-properties-cookie': 'deviceatlas-properties-cookie',
  'external-check': 'external-check',
  gid: 'gid',
  group: 'group',
  'hard-stop-after': 'hard-stop-after',
  'h1-case-adjust': 'h1-case-adjust',
  'h1-case-adjust-file': 'h1-case-adjust-file',
  'insecure-fork-wanted': 'insecure-fork-wanted',
  'insecure-setuid-wanted': 'insecure-setuid-wanted',
  'issuers-chain-path': 'issuers-chain-path',
  localpeer: 'localpeer',
  'log-send-hostname': 'log-send-hostname',
  'lua-load': 'lua-load',
  'lua-prepend-path': 'lua-prepend-path',
  'mworker-max-reloads': 'mworker-max-reloads',
  nbproc: 'nbproc',
  nbthread: 'nbthread',
  node: 'node',
  pidfile: 'pidfile',
  'pp2-never-send-local': 'pp2-never-send-local',
  presetenv: 'presetenv',
  resetenv: 'resetenv',
  uid: 'uid',
  'ulimit-n': 'ulimit-n',
  user: 'user',
  'set-dumpable': 'set-dumpable',
  setenv: 'setenv',
  stats: 'stats',
  'ssl-default-bind-ciphers': 'ssl-default-bind-ciphers',
  'ssl-default-bind-ciphersuites': 'ssl-default-bind-ciphersuites',
  'ssl-default-bind-curves': 'ssl-default-bind-curves',
  'ssl-default-bind-options': 'ssl-default-bind-options',
  'ssl-default-server-ciphers': 'ssl-default-server-ciphers',
  'ssl-default-server-ciphersuites': 'ssl-default-server-ciphersuites',
  'ssl-default-server-options': 'ssl-default-server-options',
  'ssl-dh-param-file': 'ssl-dh-param-file',
  'ssl-server-verify': 'ssl-server-verify',
  'ssl-skip-self-issued-ca': 'ssl-skip-self-issued-ca',
  'unix-bind': 'unix-bind',
  unsetenv: 'unsetenv',
  '51degrees-data-file': '51degrees-data-file',
  '51degrees-property-name-list': '51degrees-property-name-list',
  '51degrees-property-separator': '51degrees-property-separator',
  '51degrees-cache-size': '51degrees-cache-size',
  'wurfl-data-file': 'wurfl-data-file',
  'wurfl-information-list': 'wurfl-information-list',
  'wurfl-information-list-separator': 'wurfl-information-list-separator',
  'wurfl-cache-size': 'wurfl-cache-size',
  'strict-limits': 'strict-limits',
  'busy-polling': 'busy-polling',
  'max-spread-checks': 'max-spread-checks',
  maxconnrate: 'maxconnrate',
  maxcomprate: 'maxcomprate',
  maxcompcpuusage: 'maxcompcpuusage',
  maxpipes: 'maxpipes',
  maxsessrate: 'maxsessrate',
  maxsslconn: 'maxsslconn',
  maxsslrate: 'maxsslrate',
  maxzlibmem: 'maxzlibmem',
  noepoll: 'noepoll',
  nokqueue: 'nokqueue',
  noevports: 'noevports',
  nopoll: 'nopoll',
  nosplice: 'nosplice',
  nogetaddrinfo: 'nogetaddrinfo',
  noreuseport: 'noreuseport',
  'profiling.tasks': 'profiling.tasks',
  'spread-checks': 'spread-checks',
  'server-state-base': 'server-state-base',
  'server-state-file': 'server-state-file',
  'ssl-engine': 'ssl-engine',
  'ssl-mode-async': 'ssl-mode-async',
  'tune.buffers.limit': 'tune.buffers.limit',
  'tune.buffers.reserve': 'tune.buffers.reserve',
  'tune.bufsize': 'tune.bufsize',
  'tune.chksize': 'tune.chksize',
  'tune.comp.maxlevel': 'tune.comp.maxlevel',
  'tune.fd.edge-triggered': 'tune.fd.edge-triggered',
  'tune.h2.header-table-size': 'tune.h2.header-table-size',
  'tune.h2.initial-window-size': 'tune.h2.initial-window-size',
  'tune.h2.max-concurrent-streams': 'tune.h2.max-concurrent-streams',
  'tune.http.cookielen': 'tune.http.cookielen',
  'tune.http.logurilen': 'tune.http.logurilen',
  'tune.http.maxhdr': 'tune.http.maxhdr',
  'tune.idle-pool.shared': 'tune.idle-pool.shared',
  'tune.idletimer': 'tune.idletimer',
  'tune.lua.forced-yield': 'tune.lua.forced-yield',
  'tune.lua.maxmem': 'tune.lua.maxmem',
  'tune.lua.session-timeout': 'tune.lua.session-timeout',
  'tune.lua.task-timeout': 'tune.lua.task-timeout',
  'tune.lua.service-timeout': 'tune.lua.service-timeout',
  'tune.maxaccept': 'tune.maxaccept',
  'tune.maxpollevents': 'tune.maxpollevents',
  'tune.maxrewrite': 'tune.maxrewrite',
  'tune.pattern.cache-size': 'tune.pattern.cache-size',
  'tune.pipesize': 'tune.pipesize',
  'tune.pool-high-fd-ratio': 'tune.pool-high-fd-ratio',
  'tune.pool-low-fd-ratio': 'tune.pool-low-fd-ratio',
  'tune.rcvbuf.client': 'tune.rcvbuf.client',
  'tune.rcvbuf.server': 'tune.rcvbuf.server',
  'tune.recv_enough': 'tune.recv_enough',
  'tune.runqueue-depth': 'tune.runqueue-depth',
  'tune.sched.low-latency': 'tune.sched.low-latency',
  'tune.sndbuf.client': 'tune.sndbuf.client',
  'tune.sndbuf.server': 'tune.sndbuf.server',
  'tune.ssl.cachesize': 'tune.ssl.cachesize',
  'tune.ssl.keylog': 'tune.ssl.keylog',
  'tune.ssl.lifetime': 'tune.ssl.lifetime',
  'tune.ssl.force-private-cache': 'tune.ssl.force-private-cache',
  'tune.ssl.maxrecord': 'tune.ssl.maxrecord',
  'tune.ssl.default-dh-param': 'tune.ssl.default-dh-param',
  'tune.ssl.ssl-ctx-cache-size': 'tune.ssl.ssl-ctx-cache-size',
  'tune.ssl.capture-cipherlist-size': 'tune.ssl.capture-cipherlist-size',
  'tune.vars.global-max-size': 'tune.vars.global-max-size',
  'tune.vars.proc-max-size': 'tune.vars.proc-max-size',
  'tune.vars.reqres-max-size': 'tune.vars.reqres-max-size',
  'tune.vars.sess-max-size': 'tune.vars.sess-max-size',
  'tune.vars.txn-max-size': 'tune.vars.txn-max-size',
  'tune.zlib.memlevel': 'tune.zlib.memlevel',
  'tune.zlib.windowsize': 'tune.zlib.windowsize',
  quiet: 'quiet',
  'zero-warning': 'zero-warning'
};
