export const allowedOptionKeys = [
  'acl',
  'backlog',
  'bind',
  'bind-process',
  'capture cookie',
  'capture request header',
  'capture response header',
  'clitcpka-cnt',
  'clitcpka-idle',
  'clitcpka-intvl',
  'compression',
  'declare capture',
  'default_backend',
  'description',
  'disabled',
  'email-alert from',
  'keyword	defaults	frontend	listen	backend',
  'email-alert level',
  'email-alert mailers',
  'email-alert myhostname',
  'email-alert to',
  'enabled',
  'errorfile',
  'errorfiles',
  'errorloc',
  'errorloc302',
  'errorloc303',
  'filter',
  'grace',
  'http-after-response',
  'http-error',
  'http-request',
  'http-response',
  'id',
  'log',
  'log-format',
  'log-format-sd',
  'log-tag',
  'maxconn',
  'mode',
  'monitor fail',
  'monitor-uri',
  'option accept-invalid-http-request',
  'option clitcpka',
  'option contstats',
  'option disable-h2-upgrade',
  'option dontlog-normal',
  'option dontlognull',
  'option forwardfor',
  'option h1-case-adjust-bogus-client',
  'option http-buffer-request',
  'option http-ignore-probes',
  'option http-keep-alive',
  'option http-no-delay',
  'option http-server-close',
  'option http-use-proxy-header',
  'option httpclose',
  'option httplog',
  'option http_proxy',
  'option independent-streams',
  'option log-separate-errors',
  'option logasap',
  'option nolinger',
  'option originalto',
  'option socket-stats',
  'option splice-auto',
  'option splice-request',
  'option splice-response',
  'option tcp-smart-accept',
  'option tcpka',
  'option tcplog',
  'rate-limit sessions',
  'redirect',
  'stats admin',
  'stats auth',
  'stats enable',
  'stats hide-version',
  'stats http-request',
  'stats realm',
  'stats refresh',
  'stats scope',
  'stats show-desc',
  'stats show-legends',
  'stats show-node',
  'stats uri',
  'stick-table',
  'tcp-request connection',
  'tcp-request content',
  'tcp-request inspect-delay',
  'tcp-request session',
  'timeout client',
  'timeout client-fin',
  'timeout http-keep-alive',
  'timeout http-request',
  'timeout tarpit',
  'unique-id-format',
  'unique-id-header',
  'use_backend',
];
